name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: ["main", "dev"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main", "dev"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: downcaserepo
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_NAME }}

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: "v2.2.4"

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ steps.downcaserepo.outputs.lowercase }}

      # Tags
      - name: Determine tags
        id: tags
        run: |
          if [[ "${GITHUB_REF}"  == refs/heads/main ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}"  == refs/heads/dev ]]; then
            echo "tag=beta" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}"  == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF#refs/tags/v}"
            echo "tag=${VERSION}" >> $GITHUB_OUTPUT
            echo "is_release=true"
          else
            echo "tag=pr-${{ github.run_id }}" >> $GITHUB_OUTPUT
          fi

      # Build and push Docker images with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action

      # server
      - name: Build and push server
        id: build-and-push-server
        uses: docker/build-push-action@v5
        with:
          context: ./server
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ steps.downcaserepo.outputs.lowercase }}-server:${{ steps.tags.outputs.tag }}

      # client
      - name: Build and push client
        id: build-and-push-client
        uses: docker/build-push-action@v5
        with:
          context: ./client
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ steps.downcaserepo.outputs.lowercase }}-client:${{ steps.tags.outputs.tag }}

      # mqtt_publisher
      - name: Build and push mqtt_publisher
        id: build-and-push-publisher
        uses: docker/build-push-action@v5
        with:
          context: ./mqtt_publisher
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ steps.downcaserepo.outputs.lowercase }}-mqtt_publisher:${{ steps.tags.outputs.tag }}

      # Sign the resulting Docker images' digests except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign

      # Sign server
      - name: Sign server
        if: ${{ github.event_name != 'pull_request' }}
        env:
          IMAGE_TAG: ${{ env.REGISTRY }}/${{ steps.downcaserepo.outputs.lowercase }}-server:${{ steps.tags.outputs.tag }}
          DIGEST: ${{ steps.build-and-push-server.outputs.digest }}
        run: echo "${IMAGE_TAG}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      # Sign client
      - name: Sign client
        if: ${{ github.event_name != 'pull_request' }}
        env:
          IMAGE_TAG: ${{ env.REGISTRY }}/${{ steps.downcaserepo.outputs.lowercase }}-client:${{ steps.tags.outputs.tag }}
          DIGEST: ${{ steps.build-and-push-client.outputs.digest }}
        run: echo "${IMAGE_TAG}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      # Sign mqtt_publisher
      - name: Sign mqtt_publisher
        if: ${{ github.event_name != 'pull_request' }}
        env:
          IMAGE_TAG: ${{ env.REGISTRY }}/${{ steps.downcaserepo.outputs.lowercase }}-mqtt_publisher:${{ steps.tags.outputs.tag }}
          DIGEST: ${{ steps.build-and-push-publisher.outputs.digest }}
        run: echo "${IMAGE_TAG}" | xargs -I {} cosign sign --yes {}@${DIGEST}
